services:
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: aggregator
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://mongo:27017/scholarshipdb
    command: ["python", "crawler/aggregator.py"]
    networks:
      - scholarship-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: worker
    shm_size: '4gb'
    mem_limit: 16g
    memswap_limit: 16g
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://mongo:27017/scholarshipdb
    command: ["python", "crawler/worker.py"]
#    command: ["python", "crawler/test_worker.py"]
    networks:
      - scholarship-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - scholarship-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - scholarship-net

networks:
  scholarship-net:
    driver: bridge
    name: scholarship-net